"""add dollar balance

Revision ID: 5205b51d4f89
Revises: 9c69d59732ea
Create Date: 2023-05-16 13:03:09.231893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5205b51d4f89'
down_revision = '9c69d59732ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('balance', sa.String(), nullable=True))
    op.add_column('Users', sa.Column('dollar_balance', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'dollar_balance')
    op.drop_column('Users', 'balance')
    # ### end Alembic commands ###
