"""Added data table

Revision ID: 8dddb384d6d2
Revises: ff5cea82e276
Create Date: 2023-02-01 16:28:19.393398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dddb384d6d2'
down_revision = 'ff5cea82e276'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
