"""dd

Revision ID: 9c69d59732ea
Revises: 10584cce0db4
Create Date: 2023-05-11 14:06:49.849547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c69d59732ea'
down_revision = '10584cce0db4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_cards', sa.Column('card_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_cards', 'card_number')
    # ### end Alembic commands ###
