"""initial

Revision ID: b147af7928fa
Revises: 6e65fb7fec55
Create Date: 2023-05-10 08:22:56.351372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b147af7928fa'
down_revision = '6e65fb7fec55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
