"""add dollar balancsse

Revision ID: b7908ff5a571
Revises: 5205b51d4f89
Create Date: 2023-05-16 13:22:38.561934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7908ff5a571'
down_revision = '5205b51d4f89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_cards', sa.Column('reference', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_cards', 'reference')
    # ### end Alembic commands ###
